### ISSUE TITLE
AttributeError: type object 'ICatalog' has no attribute '__iro__'

### ISSUE THREAD

**Issue by hvelarde** [collective/collective.cover#816]
This issue is a placeholder for answering a question that is going be be raised by people upgrading collective.cover without reading the documentation.

You'll see the following error after upgrading from 1.7b3 to 2.0a1:

```
2018-08-23 22:45:26 INFO Zope Ready to handle requests
2018-08-23 22:45:26 WARNING OFS.Uninstalled Could not import class 'IntIds' from module 'five.intid.intid'
2018-08-23 22:45:26 WARNING OFS.Uninstalled Could not import class 'RelationCatalog' from module 'z3c.relationfield.index'
2018-08-23 22:45:26 WARNING OFS.Uninstalled Could not import class 'ICatalog' from module 'zc.relation.interfaces'
2018-08-23 22:45:26 WARNING OFS.Uninstalled Could not import class 'IIntIds' from module 'zope.intid.interfaces'
2018-08-23 22:45:26 ERROR ZODB.Connection Couldn't load state for 0xea45
Traceback (most recent call last):
  File "/opt/plone/buildout/eggs/ZODB3-3.10.7-py2.7-linux-x86_64.egg/ZODB/Connection.py", line 860, in setstate
    self._setstate(obj)
  File "/opt/plone/buildout/eggs/ZODB3-3.10.7-py2.7-linux-x86_64.egg/ZODB/Connection.py", line 914, in _setstate
    self._reader.setGhostState(obj, p)
  File "/opt/plone/buildout/eggs/ZODB3-3.10.7-py2.7-linux-x86_64.egg/ZODB/serialize.py", line 613, in setGhostState
    obj.__setstate__(state)
  File "/opt/plone/buildout/eggs/zope.component-3.9.5-py2.7.egg/zope/component/persistentregistry.py", line 40, in __setstate__
    self._createLookup()
  File "/opt/plone/buildout/eggs/zope.interface-3.6.7-py2.7-linux-x86_64.egg/zope/interface/adapter.py", line 91, in _createLookup
    self._v_lookup = self.LookupClass(self)
  File "/opt/plone/buildout/eggs/zope.interface-3.6.7-py2.7-linux-x86_64.egg/zope/interface/adapter.py", line 439, in __init__
    self.init_extendors()
  File "/opt/plone/buildout/eggs/zope.interface-3.6.7-py2.7-linux-x86_64.egg/zope/interface/adapter.py", line 476, in init_extendors
    self.add_extendor(p)
  File "/opt/plone/buildout/eggs/zope.interface-3.6.7-py2.7-linux-x86_64.egg/zope/interface/adapter.py", line 480, in add_extendor
    for i in provided.__iro__:
AttributeError: type object 'ICatalog' has no attribute '__iro__'
2018-08-23 22:45:26 ERROR Zope.SiteErrorLog 1535075126.960.378729390147 http://localhost:8080/1.7b3
Traceback (innermost last):
  Module ZPublisher.Publish, line 127, in publish
  Module ZPublisher.BaseRequest, line 444, in traverse
  Module ZPublisher.BeforeTraverse, line 97, in __call__
  Module Products.CMFCore.PortalObject, line 75, in __before_publishing_traverse__
  Module zope.event, line 31, in notify
  Module zope.component.event, line 24, in dispatch
  Module zope.component._api, line 136, in subscribers
  Module zope.component.registry, line 321, in subscribers
  Module zope.interface.adapter, line 585, in subscribers
  Module zope.component.event, line 32, in objectEventNotify
  Module zope.component._api, line 136, in subscribers
  Module zope.component.registry, line 321, in subscribers
  Module zope.interface.adapter, line 585, in subscribers
  Module plone.app.theming.plugins.hooks, line 30, in onRequest
  Module plone.app.theming.utils, line 429, in isThemeEnabled
  Module zope.component._api, line 172, in queryUtility
  Module zope.component.registry, line 163, in queryUtility
SystemError: error return without exception set
2018-08-23 22:45:26 ERROR ZODB.Connection Couldn't load state for 0xea45
Traceback (most recent call last):
  File "/opt/plone/buildout/eggs/ZODB3-3.10.7-py2.7-linux-x86_64.egg/ZODB/Connection.py", line 860, in setstate
    self._setstate(obj)
  File "/opt/plone/buildout/eggs/ZODB3-3.10.7-py2.7-linux-x86_64.egg/ZODB/Connection.py", line 914, in _setstate
    self._reader.setGhostState(obj, p)
  File "/opt/plone/buildout/eggs/ZODB3-3.10.7-py2.7-linux-x86_64.egg/ZODB/serialize.py", line 613, in setGhostState
    obj.__setstate__(state)
  File "/opt/plone/buildout/eggs/zope.component-3.9.5-py2.7.egg/zope/component/persistentregistry.py", line 40, in __setstate__
    self._createLookup()
  File "/opt/plone/buildout/eggs/zope.interface-3.6.7-py2.7-linux-x86_64.egg/zope/interface/adapter.py", line 91, in _createLookup
    self._v_lookup = self.LookupClass(self)
  File "/opt/plone/buildout/eggs/zope.interface-3.6.7-py2.7-linux-x86_64.egg/zope/interface/adapter.py", line 439, in __init__
    self.init_extendors()
  File "/opt/plone/buildout/eggs/zope.interface-3.6.7-py2.7-linux-x86_64.egg/zope/interface/adapter.py", line 476, in init_extendors
    self.add_extendor(p)
  File "/opt/plone/buildout/eggs/zope.interface-3.6.7-py2.7-linux-x86_64.egg/zope/interface/adapter.py", line 480, in add_extendor
    for i in provided.__iro__:
AttributeError: type object 'ICatalog' has no attribute '__iro__'
```

**Comment by hvelarde** [comment]
The error above indicates you forgot to add the `[relations]` extra to your buildout configuration:

```ini
[buildout]
eggs =
    collective.cover [relations]
```

Next time you upgrade to a major version, be sure you read the documentation and understand what are you doing before acting.
